language: csharp
script:
  - xbuild /p:Configuration=Release MailDelivery.sln
branches:
  only:
  - master
before_deploy:
  - cd /home/travis/build/d0p3t/MailDelivery/MailDelivery.Client/bin/Release/ && rm *.pdb && rm CitizenFX.Client.dll
  - wget https://d0p3t.nu/maildelivery/__resource.lua
  - zip -r maildelivery-$TRAVIS_TAG.zip *
deploy:
  provider: releases
  api_key: $DEPLOY_KEY
  file: "/home/travis/build/d0p3t/MailDelivery/MailDelivery.Client/bin/Release/maildelivery-$TRAVIS_TAG.zip"
  skip_cleanup: true
  prerelease: false
  draft: true
  name: "MailDelivery $TRAVIS_TAG"
  on:
    repo: d0p3t/MailDelivery
    tags: true
after_deploy:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"
