language: csharp
script:
  - xbuild /p:Configuration=Release MailDelivery.sln
branches:
  only:
  - master
before_deploy:
  - cd /home/travis/build/d0p3t/MailDelivery/MailDelivery.Client/bin/Release/ && rm *.pdb && rm CitizenFX.Client.dll
  - wget https://d0p3t.nu/maildelivery/__resource.lua
  - version=`cat __resource.lua | grep "version " | tail -n 1 | cut -d ' ' -f 2 | cut -c 2- | rev | cut -c 3- | rev`
  - zip -r maildelivery-$version.zip *
  - cd /home/travis/build/d0p3t/MailDelivery/MailDelivery.Client/bin/Release/ && git config --local user.name "d0p3t"
  - cd /home/travis/build/d0p3t/MailDelivery/MailDelivery.Client/bin/Release/ && git config --local user.email "d0p3t@users.noreply.github.com"
  - cd /home/travis/build/d0p3t/MailDelivery/MailDelivery.Client/bin/Release/ && git tag $version
deploy:
  provider: releases
  api_key:
    secure: $DEPLOY_KEY
  file: "/home/travis/build/d0p3t/MailDelivery/MailDelivery.Client/bin/Release/maildelivery-$version.zip"
  skip_cleanup: true
  prerelease: false
  draft: true
  name: "MailDelivery $version"
  on:
    repo: d0p3t/MailDelivery
    branch:
      - master
after_success:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"
