trigger:
  batch: true
  tags:
    include:
    - v*
  branches:
    include:
    - master

pr:
- master
 
pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  displayName: 'Restore NuGet'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    msbuildArgs: /p:DeployOnBuild=true /p:SkipInvalidConfigurations=true'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- script: |
    echo "Copy build to staging"
    dir $(Build.SourcesDirectory)\MailDelivery.Client\bin\Release\
    xcopy $(Build.SourcesDirectory)\MailDelivery.Client\bin\Release\MailDelivery.Client.net.dll $(Build.ArtifactStagingDirectory)

- script: |
    echo "Copy __resource.lua"
    xcopy $(Build.SourcesDirectory)\__resource.lua $(Build.ArtifactStagingDirectory)
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    artifactName: 'maildelivery' 